import {
  TrendingUp, Crosshair, Lightbulb, Bot, Search, Play, ShieldAlert,
  PackageSearch, BarChart3, Users, Truck, DollarSign, Wrench, Zap
} from 'lucide-react';

export const AGENT_TEMPLATES = [
  {
    key: 'demand_forecasting',
    label: 'Demand Forecasting',
    icon: TrendingUp,
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    agentType: 'forecast',
    domain: 'Manufacturing · Retail',
    desc: 'Predicts future demand using historical sales, seasonal trends, and external signals. Surfaces inventory gaps before they impact service levels.',
    agents: ['Forecast', 'Detection', 'Recommendation'],
    tags: ['Retail', 'Manufacturing', 'Inventory'],
  },
  {
    key: 'supply_chain_diagnosis',
    label: 'Supply Chain Diagnosis',
    icon: Crosshair,
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
    agentType: 'diagnosis',
    domain: 'Logistics · Operations',
    desc: 'Identifies root causes of supply disruptions, delays, and quality failures across Tier-1 and Tier-2 suppliers using causal reasoning.',
    agents: ['Detection', 'Diagnosis', 'Recommendation'],
    tags: ['Supply Chain', 'Logistics', 'Risk'],
  },
  {
    key: 'anomaly_detection',
    label: 'KPI Anomaly Detection',
    icon: Search,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    agentType: 'detection',
    domain: 'Finance · Operations',
    desc: 'Continuously monitors KPI streams and triggers alerts when values deviate from expected ranges, with severity scoring and root cause hints.',
    agents: ['Detection', 'Diagnosis'],
    tags: ['Finance', 'Operations', 'Monitoring'],
  },
  {
    key: 'risk_management',
    label: 'Risk & Compliance Monitor',
    icon: ShieldAlert,
    color: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    agentType: 'detection',
    domain: 'Finance · HR',
    desc: 'Tracks regulatory, financial, and operational risk signals. Surfaces compliance gaps and recommends remediation steps in real time.',
    agents: ['Detection', 'Diagnosis', 'Recommendation', 'Execution'],
    tags: ['Finance', 'HR', 'Compliance'],
  },
  {
    key: 'inventory_optimisation',
    label: 'Inventory Optimisation',
    icon: PackageSearch,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    agentType: 'recommendation',
    domain: 'Logistics · Retail',
    desc: 'Balances stock levels across warehouses and SKUs to minimise holding costs while preventing stockouts and overstock situations.',
    agents: ['Forecast', 'Recommendation', 'Execution'],
    tags: ['Retail', 'Logistics', 'Inventory'],
  },
  {
    key: 'workforce_planning',
    label: 'Workforce Planning',
    icon: Users,
    color: 'text-indigo-400',
    bg: 'bg-indigo-500/10',
    border: 'border-indigo-500/30',
    agentType: 'forecast',
    domain: 'HR · Operations',
    desc: 'Forecasts headcount needs by role and region, identifies skills gaps, and recommends hiring or retraining plans aligned to business goals.',
    agents: ['Forecast', 'Recommendation'],
    tags: ['HR', 'Operations', 'Planning'],
  },
  {
    key: 'logistics_delay',
    label: 'Last-Mile Logistics Agent',
    icon: Truck,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/30',
    agentType: 'execution',
    domain: 'Logistics',
    desc: 'Monitors shipment ETAs in real time, detects delays, reroutes deliveries, and coordinates carrier communication automatically.',
    agents: ['Detection', 'Execution', 'Learning'],
    tags: ['Logistics', 'Delivery', 'Automation'],
  },
  {
    key: 'financial_close',
    label: 'Financial Close Accelerator',
    icon: DollarSign,
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    agentType: 'execution',
    domain: 'Finance',
    desc: 'Automates period-end reconciliation tasks, flags discrepancies, and accelerates the close cycle with guided resolution workflows.',
    agents: ['Detection', 'Recommendation', 'Execution'],
    tags: ['Finance', 'Accounting', 'Automation'],
  },
  {
    key: 'maintenance_prediction',
    label: 'Predictive Maintenance',
    icon: Wrench,
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    agentType: 'forecast',
    domain: 'Manufacturing · Operations',
    desc: 'Ingests IoT sensor data to predict equipment failures before they occur, schedules maintenance proactively, and reduces unplanned downtime.',
    agents: ['Detection', 'Forecast', 'Execution'],
    tags: ['Manufacturing', 'IoT', 'Maintenance'],
  },
  {
    key: 'revenue_intelligence',
    label: 'Revenue Intelligence',
    icon: BarChart3,
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
    border: 'border-pink-500/30',
    agentType: 'recommendation',
    domain: 'Finance · Retail',
    desc: 'Analyses pipeline, pricing, and churn signals to surface upsell opportunities and at-risk accounts, with prioritised sales actions.',
    agents: ['Detection', 'Forecast', 'Recommendation'],
    tags: ['Finance', 'Sales', 'Revenue'],
  },
];